# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: CI

on:
  - pull_request
  - push

env:
  XDEBUG_MODE: coverage

jobs:
  type-checker:
    name: Type Checker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Install PHP
        uses: shivammathur/setup-php@2.25.0
        with:
          tools: phpunit
          php-version: 8.2

      - name: Set up cache for Composer dependencies
        uses: actions/cache@v3.3.1
        with:
          path: "${{ github.workspace }}/.composer/cache"
          key: "${{ runner.os }}-path"

      - name: Install dependencies with Composer
        run: composer install --no-interaction --prefer-source

      - name: Run Psalm
        run: vendor/bin/psalm --config=.psalm/config.xml --no-progress --shepherd --show-info=false --stats

  unit-tests:
    name: Unit Tests

    needs:
      - type-checker

    runs-on: ${{ matrix.os }}

    env:
      PHP_EXTENSIONS: none, curl, dom, mbstring, simplexml, xml, xmlwriter, zlib

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0

    - name: Install PHP
      uses: shivammathur/setup-php@2.25.0
      with:
        tools: phpunit
        php-version: "${{ matrix.php }}"
        extensions: ${{ env.PHP_EXTENSIONS }}

    - name: Set up cache for Composer dependencies
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.composer/cache"
        key: "${{ runner.os }}-path"

    - name: Install dependencies with Composer
      run: composer install --no-interaction --prefer-source

    - name: Set up cache for tests results
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/tests/cache"
        key: "${{ runner.os }}-path"

    - name: Run tests
      run: vendor/bin/phpunit --coverage-clover=tests/cache/coverage.xml

  code-coverage:
    name: Code Coverage

    needs:
      - unit-tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Set up cache for tests results
        uses: actions/cache@v3.3.1
        with:
          path: "${{ github.workspace }}/tests/cache"
          key: "${{ runner.os }}-path"

      - run: bash <(curl -s https://codecov.io/bash) -f tests/cache/coverage.xml